### ISSUE TITLE
geo_join warning

### ISSUE THREAD

**Issue by sisiraul** [walkerke/tigris#167] opened 2023-05-02 02:18 UTC
Hi,
I got the below warning while running geo_join. Just want to report it here as instructed below.

Warning messages:
1: We recommend using the dplyr::*_join() family of functions instead. 
2: `group_by_()` was deprecated in dplyr 0.7.0.
ℹ Please use `group_by()` instead.
ℹ See vignette('programming') for more help
ℹ The deprecated feature was likely used in the tigris package.
  Please report the issue at <https://github.com/walkerke/tigris/issues>.

**Comment by lpiep** [comment] 2023-10-27 21:52
I looked at this and can reproduce it with the following code:

```
state_ranks <- data.frame(
  STUSPS = c('WA', 'OR', 'CA'),
  RANK = c('best', 'better', 'good')
)
geo_join(
  states(cb = TRUE), 
  state_ranks,
  by_sp = 'STUSPS',
  by_df = 'STUSPS'
)
```

The first warning message is coming from Tigris itself (warning you that the `geo_join` function is deprecated), and the second is from `dplyr` complaining about the usage of old syntax within that function. `dplyr` is actually the one suggesting you post in issues here. Since the `geo_join` function is deprecated I don't imagine it will be updated to use the newer `dplyr` syntax.

**Comment by walkerke** [comment] 2023-10-28 16:14
Yes, this is a deprecated function.  Closing the issue.

**Closed by walkerke** 2023-10-28 16:14 UTC
