### ISSUE TITLE
Unable to Download Shape Files

### ISSUE THREAD

**Issue by ZellW** [walkerke/tigris#14] opened 2016-01-29 14:14 UTC
I am new to R - so if this is stupid, my apologies.  A recurring error happens when the app attempts to download the share files:  

Error in ogrInfo(dsn = dsn, layer = layer, encoding = encoding, use_iconv = use_iconv,  : 
  Cannot open data source
In addition: Warning message:
In unzip(file_loc, exdir = cache_dir, overwrite = TRUE) :
  error 1 in extracting from zip file
This occurs when I run your example code:

library(tigris)
library(magrittr)
ua <- urban_areas(cb = TRUE)
plot(ua)

I really hope I can resolve this.  Your package would be tremendously useful to me!

**Comment by walkerke** [comment] 2016-01-30 04:25
Hmm.  Can you try this for me?  

```r
library(rappdirs)

user_cache_dir()
```

Navigate to that directory on your machine and see if there is a `tigris` folder there - if so, enter it and see if any datasets are found inside.  Are you on a work machine with heavy restrictions by chance?  

If nothing is writing there this may be the case.  In this instance try entering the command `options(tigris_use_cache = FALSE)` before running __tigris__ commands, as this will tell __tigris__ to download the shapefiles to a temporary directory instead, which may work.

**Comment by ZellW** [comment] 2016-01-30 14:56
Really appreciate the feedback.
Here are the results.  (I believe it might be a Windows 10 change that is causing the problem.)
Installed rappdirs.  The result of user_cache_dir() is  "C:\\Users\\czwea\\AppData\\Local\\Cache"
That folder does not exist on my machine (which I have admin rights to).  I do have this folder: 
C:\Users\czwea\AppData\Local\tigris\tigris\Cache
This folder is empty.
Entered:  options(tigris_use_cache = FALSE) 
This corrected my problem.  plot(ua) as an example works.
Your help is much appreciated.  Many thanks.
Cliff

Date: Fri, 29 Jan 2016 20:25:37 -0800

**Comment by walkerke** [comment] 2016-01-31 19:13
Ok great.  Closing the issue for now but will investigate the Windows 10 issue, the folder you've described is the folder that tigris should be writing to.

**Closed by walkerke** 2016-01-31 19:13 UTC

**Comment by k6adams** [comment] 2020-09-29 20:12
Hello @walkerke,
I am new to R and GiHub, I apologize for not formatting my code correctly.  Feel free to correct me.

I am having an issue similar to many of the posts in this thread. I work on a US government computer, so the firewall might have something to do with it, but I am not sure. For some reason, I am able to pull the standard resolution counties file, but have not had luck with any of the higher resolution options. And in my use case, the higher resolution, the better.

> library(tigris)
> options(tigris_use_cache = F)
> library(rappdirs)
> 
> county_map_shape_500k <- counties(cb = TRUE, refresh = TRUE)
> county_map_shape_20m <- counties(cb = TRUE, resolution = '20m', refresh = TRUE)
Cannot open layer cb_2019_us_county_20m
Error in CPL_read_ogr(dsn, layer, query, as.character(options), quiet,  : 
  Opening layer failed.
In addition: Warning message:
In unzip(file_loc, exdir = tmp) : error 1 in extracting from zip file
> user_cache_dir()
[1] "C:\\Users\\KEVIN~1.ADA\\AppData\\Local\\Cache"
> list.files("C:\\Users\\KEVIN~1.ADA\\AppData\\Local\\Cache")
character(0)
> tempdir()
[1] "C:\\Users\\KEVIN~1.ADA\\AppData\\Local\\Temp\\RtmpOOuulg"
> list.files("C:\\Users\\KEVIN~1.ADA\\AppData\\Local\\Temp\\Rtmp6d1ou7")
character(0)
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

**Comment by semiographics** [comment] 2023-01-10 23:48
Same problem as above.
If tigris_use_cache is set to TRUE, the download fails over and over.
If tigris_use_cache is set to FALSE, then
Error: Cannot open "...\Rtmp2NIlzp"; The source could be corrupt or not supported. See `st_drivers()` for a list of supported formats.
In addition: Warning message:
In unzip(file_loc, exdir = tmp) : error 1 in extracting from zip file
I've gone around in circles for 2 hours.  Installed the dev version, done everything everyone has suggested.

**Comment by walkerke** [comment] 2023-01-11 00:27
@semiographics can you post the code you've tried and the results of your `sessionInfo()`?

**Comment by semiographics** [comment] 2023-01-11 00:32
library(tigris)
library(sf)

zips <- zctas(cb=TRUE, starts_with="00601")
Retrieving data for the year 2021
Previous download failed.  Re-download attempt 1 of 3...
  |===============================================================================================================| 100%
Previous download failed.  Re-download attempt 2 of 3...
  |===============================================================================================================| 100%
Previous download failed.  Re-download attempt 3 of 3...
  |===============================================================================================================| 100%
Error: Download failed; check your internet connection or the status of the Census Bureau website
                 at http://www2.census.gov/geo/tiger/.
> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rappdirs_0.3.3  sf_1.0-9        tigris_2.0      RPostgres_1.4.4

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.9         class_7.3-19       prettyunits_1.1.1  ps_1.7.2           assertthat_0.2.1   rprojroot_2.0.3   
 [7] digest_0.6.31      utf8_1.2.2         mime_0.12          R6_2.5.1           e1071_1.7-12       httr_1.4.4        
[13] ggplot2_3.4.0      pillar_1.8.1       rlang_1.0.6        uuid_1.1-0         curl_4.3.3         rstudioapi_0.14   
[19] miniUI_0.1.1.1     callr_3.7.3        urlchecker_1.0.1   blob_1.2.3         desc_1.4.2         devtools_2.4.4    
[25] stringr_1.5.0      htmlwidgets_1.6.1  bit_4.0.5          munsell_0.5.0      proxy_0.4-27       shiny_1.7.4       
[31] compiler_4.1.2     httpuv_1.6.7       pkgconfig_2.0.3    pkgbuild_1.4.0     htmltools_0.5.4    tidyselect_1.2.0  
[37] tibble_3.1.8       fansi_1.0.3        crayon_1.5.2       dplyr_1.0.10       withr_2.5.0        later_1.3.0       
[43] grid_4.1.2         xtable_1.8-4       gtable_0.3.1       lifecycle_1.0.3    DBI_1.1.3          magrittr_2.0.3    
[49] units_0.8-1        scales_1.2.1       KernSmooth_2.23-20 cli_3.5.0          stringi_1.7.6      cachem_1.0.6      
[55] fs_1.5.2           promises_1.2.0.1   remotes_2.4.2      ellipsis_0.3.2     generics_0.1.3     vctrs_0.5.1       
[61] tools_4.1.2        bit64_4.0.5        glue_1.6.2         purrr_1.0.0        hms_1.1.2          processx_3.8.0    
[67] pkgload_1.3.2      fastmap_1.1.0      colorspace_2.0-3   sessioninfo_1.2.2  classInt_0.4-8     memoise_2.0.1     
[73] profvis_0.3.7      usethis_2.1.6

**Comment by walkerke** [comment] 2023-01-11 00:50
@semiographics Ah, I see what's going on.  The CB ZCTA file has not yet been released for 2021, so you are trying to download a file that doesn't exist. I need to put in an error message until they release it, I'll patch that shortly.  

You can still get 2020 CB ZCTAs by putting in the argument `year = 2020`.  Or, you can also get 2021 ZCTAs from the regular TIGER/Line dataset by removing the `cb = TRUE` argument.

**Comment by semiographics** [comment] 2023-01-11 00:55
Aha...
Thanks for the quick response.
You know, it's funny because I pulled the whole set from the Cartographic Boundaries page yesterday and I recall that I had to go to the 2020 tab.
Here I am trying to help somebody on stackexchange who apparently doesn't know how to execute a join.  Was trying to reproduce their code...
Thanks again.

**Comment by bholtdwyer** [comment] 2023-04-17 22:45
Just a bump to suggest a clearer message when maps do not exist, as @walkerke suggests. When you ask for a year that doesn't exist the resulting error is quite opaque.

`> #Trying to pull the 2003 Census shapefile in using the tigris package:
> counties_2003 = counties(state = "California", cb = TRUE, year = 2003)
  |==================================================================================| 100%
Error: Cannot open "C:\Users\holtd\AppData\Local\Temp\RtmpycBSep"; The source could be corrupt or not supported. See `st_drivers()` for a list of supported formats.
In addition: Warning message:
In unzip(file_loc, exdir = tmp) : error 1 in extracting from zip file
> #Trying to pull the 2003 Census shapefile in using the tigris package:
> counties_2003 = counties(state = "California", cb = TRUE, year = 2020)
  |==================================================================================| 100%
Using FIPS code '06' for state 'California'`
